####
# Purpose: Build out DC1 domain Controller
# Author: Ben Mason
#


### Required settings
$hostname = "DC1"
$domain_name = "csateng.lab"
$netbiosName = "CSATENG"
$network_interface = "Ethernet0"
$timezone = "Central Standard Time"
### Network Settings
# set $setipaddress to $true to set IP addressing
$setipaddress = $false  
$ip_Address = "10.89.49.50"
$subnet_mask = "26"
$default_gateway = "10.89.49.1"
$dns_servers = "10.89.49.50, 10.89.49.51"
$dns_forwarder1 = "10.89.49.98"
$dns_forwarder2 = "10.89.49.99"
### CA Settings
$ca_commonname ="csateng-Host1-CA-1"
$DN_Suffix = "DC=csateng,DC=lab"

####
# Purpose: Initial computer configuration
#
$stage_check = Test-Path "c:\stage1complete.txt" -PathType Leaf
if ($stage_check -eq $false) {
    Rename-Computer -NewName $hostname 
    Set-TimeZone -Id $timezone 
    # Enable RDP
    Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
    Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    if ($setipaddress -eq $true) {
        New-NetIPAddress –InterfaceAlias $network_interface –IPv4Address $ip_Address –PrefixLength $subnet_mask -DefaultGateway $default_gateway
        Set-DnsClientServerAddress -InterfaceAlias $network_interface -ServerAddresses $dns_Servers
    }
    # Set Adapter Category
    Set-NetConnectionProfile -InterfaceAlias $network_interface -NetworkCategory Private
    New-Item -Path "c:\" -Name "stage1complete.txt" -ItemType "file" -Value "Step one complete."
    Restart-Computer
}

####
# Purpose: Add Active Directory related Windows Features
# Second Step in Labnet Domain Controller Build
#
$stage_check = Test-Path "c:\stage2complete.txt" -PathType Leaf
if ($stage_check -eq $false) {

    # Reset DNS Servers from any temporary settings
    Set-DnsClientServerAddress -InterfaceAlias $network_interface -ServerAddresses $dns_servers

    # Install Features 
    Add-WindowsFeature "RSAT-AD-Tools" 
    Add-WindowsFeature -Name "ad-domain-services" -IncludeAllSubFeature -IncludeManagementTools 
    Add-WindowsFeature -Name "dns" -IncludeAllSubFeature -IncludeManagementTools 
    Add-WindowsFeature -Name "gpmc" -IncludeAllSubFeature -IncludeManagementTools

    # Source: https://github.com/DefensiveOrigins/APT06202001/blob/master/Lab-DomainBuildScripts/ADDS-Step3-Forest.ps1
    # create new forest and add domain controller
    New-Item -Path "c:\" -Name "stage2complete.txt" -ItemType "file" -Value "Step two complete."

    Import-Module ADDSDeployment
    Install-ADDSForest -CreateDnsDelegation:$false -DatabasePath "C:\Windows\NTDS" -DomainMode "WinThreshold" -DomainName $domain_name -DomainNetbiosName $netbiosName -ForestMode "Win2012" -InstallDns:$true -LogPath "C:\Windows\NTDS" -NoRebootOnCompletion:$false -SysvolPath "C:\Windows\SYSVOL" -Force:$true

}

####
# Purpose: Setup Certifate Services and create simulated users
# 3rd Step in Labnet Domain Controller Build
#
$stage_check = Test-Path "c:\stage2complete.txt" -PathType Leaf
if ($stage_check -eq $true) {

    # Set DNS Forwarders
    Set-DnsServerForwarder -IPAddress $dns_forwarder1 -PassThru
    Add-DnsServerForwarder -IPAddress $dns_forwarder2 -PassThru

    # Enable Certificate services
    Add-WindowsFeature -Name "AD-Certificate" -IncludeAllSubFeature -IncludeManagementTools
    Install-WindowsFeature ADCS-Cert-Authority -IncludeManagementTools
    Install-ADcsCertificationAuthority -Credential (Get-Credential) -CAType StandaloneRootCA -CACommonName $ca_commonname -CADistinguishedNameSuffix $DN_Suffix -CryptoProviderName "RSA#Microsoft Software Key Storage Provider" -KeyLength 2048 -HashAlgorithmName SHA1 -ValidityPeriod Years -ValidityPeriodUnits 3 -DatabaseDirectory "C:\windows\system32\certLog" -LogDirectory "c:\windows\system32\CertLog" –Force

    # Source: https://github.com/DefensiveOrigins/APT06202001/blob/master/Lab-DomainBuildScripts/ADDS-Step4-AddUsers.ps1
    New-ADOrganizationalUnit -Name "UserAccounts"
    New-ADOrganizationalUnit -Name "ComputerAccounts"
    New-ADOrganizationalUnit -Name "AdminAccounts"
    DSADD user -upn itadmin@csateng.lab "cn=itadmin,ou=AdminAccounts,dc=csateng,dc=lab" -fn "it" -ln "admin" -disabled no -display "ITAdmin" -desc "Non-Destruct Medieval Architecture Specialist" -office "Administration" -title "Controller" -company "DevLabs" -PWD "ThisShouldBeLongerThan20"
    Add-ADGroupMember -Identity "Domain Admins" -Members itadmin
    DSADD user -upn Luis.Graves@csateng.lab "cn=Luis.Graves,ou=UserAccounts,dc=csateng,dc=lab" -fn "Luis" -ln "Graves" -disabled no -display "Luis Graves" -desc "Accounting Controller" -office "Accounting" -title "Controller" -company "DevLabs" -PWD "Badpass76918"
    DSADD user -upn Pam.Sparks@csateng.lab "cn=Pam.Sparks,ou=UserAccounts,dc=csateng,dc=lab" -fn "Pam" -ln "Sparks" -disabled no -display "Pam Sparks" -desc "Accounting Accounts Payable" -office "DevLabs Accounting" -title "Accounts Payable" -company "DevLabs" -PWD "Badpass30886"
    DSADD user -upn Jesus.Robertson@csateng.lab "cn=Jesus.Robertson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Jesus" -ln "Robertson" -disabled no -display "Jesus Robertson" -desc "Accounting Accounts Receivable" -office "DevLabs Accounting" -title "Accounts Receivable" -company "DevLabs" -PWD "Badpass33835"
    DSADD user -upn Nellie.Blair@csateng.lab "cn=Nellie.Blair,ou=UserAccounts,dc=csateng,dc=lab" -fn "Nellie" -ln "Blair" -disabled no -display "Nellie Blair" -desc "WholeSales Wholesale Sales" -office "DevLabs WholeSales" -title "Wholesale Sales" -company "DevLabs" -PWD "Badpass22601"
    DSADD user -upn Carl.Pearson@csateng.lab "cn=Carl.Pearson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Carl" -ln "Pearson" -disabled no -display "Carl Pearson" -desc "WholeSales Wholesale Sales" -office "DevLabs WholeSales" -title "Wholesale Sales" -company "DevLabs" -PWD "Badpass23644"
    DSADD user -upn Geneva.Bryant@csateng.lab "cn=Geneva.Bryant,ou=UserAccounts,dc=csateng,dc=lab" -fn "Geneva" -ln "Bryant" -disabled no -display "Geneva Bryant" -desc "WholeSales Wholesale Sales" -office "DevLabs WholeSales" -title "Wholesale Sales" -company "DevLabs" -PWD "Badpass59456"
    DSADD user -upn Diana.Henderson@csateng.lab "cn=Diana.Henderson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Diana" -ln "Henderson" -disabled no -display "Diana Henderson" -desc "Transportaion Logistics Manager" -office "DevLabs Transportaion" -title "Logistics Manager" -company "DevLabs" -PWD "Badpass82796"
    DSADD user -upn Courtney.Mitchell@csateng.lab "cn=Courtney.Mitchell,ou=UserAccounts,dc=csateng,dc=lab" -fn "Courtney" -ln "Mitchell" -disabled no -display "Courtney Mitchell" -desc "Transportation Logistics Assistant" -office "DevLabs Transportation" -title "Logistics Assistant" -company "DevLabs" -PWD "Badpass77145"
    DSADD user -upn Gina.Hampton@csateng.lab "cn=Gina.Hampton,ou=UserAccounts,dc=csateng,dc=lab" -fn "Gina" -ln "Hampton" -disabled no -display "Gina Hampton" -desc "Bakery Production Director of Bakering" -office "DevLabs Bakery Production" -title "Director of Bakering" -company "DevLabs" -PWD "Badpass94578"
    DSADD user -upn Otis.Mullins@csateng.lab "cn=Otis.Mullins,ou=UserAccounts,dc=csateng,dc=lab" -fn "Otis" -ln "Mullins" -disabled no -display "Otis Mullins" -desc "Bakery Production Head Baker" -office "DevLabs Bakery Production" -title "Head Baker" -company "DevLabs" -PWD "Badpass46747"
    DSADD user -upn Gordon.Phillips@csateng.lab "cn=Gordon.Phillips,ou=UserAccounts,dc=csateng,dc=lab" -fn "Gordon" -ln "Phillips" -disabled no -display "Gordon Phillips" -desc "Bakery Production Head Baker" -office "DevLabs Bakery Production" -title "Head Baker" -company "DevLabs" -PWD "Badpass59314"
    DSADD user -upn Olive.Ross@csateng.lab "cn=Olive.Ross,ou=UserAccounts,dc=csateng,dc=lab" -fn "Olive" -ln "Ross" -disabled no -display "Olive Ross" -desc "Bakery Production Baker" -office "DevLabs Bakery Production" -title "Baker" -company "DevLabs" -PWD "Badpass23913"
    DSADD user -upn Roxanne.Greer@csateng.lab "cn=Roxanne.Greer,ou=UserAccounts,dc=csateng,dc=lab" -fn "Roxanne" -ln "Greer" -disabled no -display "Roxanne Greer" -desc "Bakery Production Baker" -office "DevLabs Bakery Production" -title "Baker" -company "DevLabs" -PWD "Badpass65009"
    DSADD user -upn Willie.Herrera@csateng.lab "cn=Willie.Herrera,ou=UserAccounts,dc=csateng,dc=lab" -fn "Willie" -ln "Herrera" -disabled no -display "Willie Herrera" -desc "Bakery Production Baker" -office "DevLabs Bakery Production" -title "Baker" -company "DevLabs" -PWD "Badpass89503"
    DSADD user -upn Randal.Simpson@csateng.lab "cn=Randal.Simpson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Randal" -ln "Simpson" -disabled no -display "Randal Simpson" -desc "Bakery Production Baker" -office "DevLabs Bakery Production" -title "Baker" -company "DevLabs" -PWD "Badpass32673"
    DSADD user -upn Bradley.Christensen@csateng.lab "cn=Bradley.Christensen,ou=UserAccounts,dc=csateng,dc=lab" -fn "Bradley" -ln "Christensen" -disabled no -display "Bradley Christensen" -desc "Bakery Production Baker" -office "DevLabs Bakery Production" -title "Baker" -company "DevLabs" -PWD "Badpass67659"
    DSADD user -upn Heather.Butler@csateng.lab "cn=Heather.Butler,ou=UserAccounts,dc=csateng,dc=lab" -fn "Heather" -ln "Butler" -disabled no -display "Heather Butler" -desc "Bakery Production Purchasing Agent" -office "DevLabs Bakery Production" -title "Purchasing Agent" -company "DevLabs" -PWD "Badpass25808"
    DSADD user -upn Elisa.Lawson@csateng.lab "cn=Elisa.Lawson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Elisa" -ln "Lawson" -disabled no -display "Elisa Lawson" -desc "Bakery Production Confectionary Specialist" -office "DevLabs Bakery Production" -title "Confectionary Specialist" -company "DevLabs" -PWD "Badpass93896"
    DSADD user -upn Kristi.Silva@csateng.lab "cn=Kristi.Silva,ou=UserAccounts,dc=csateng,dc=lab" -fn "Kristi" -ln "Silva" -disabled no -display "Kristi Silva" -desc "Bakery Production Confectionary Specialist" -office "DevLabs Bakery Production" -title "Confectionary Specialist" -company "DevLabs" -PWD "Badpass66729"
    DSADD user -upn Ed.Barnes@csateng.lab "cn=Ed.Barnes,ou=UserAccounts,dc=csateng,dc=lab" -fn "Ed" -ln "Barnes" -disabled no -display "Ed Barnes" -desc "BusAdmin Office Manager" -office "DevLabs BusAdmin" -title "Office Manager" -company "DevLabs" -PWD "Badpass21561"
    DSADD user -upn Angela.Garner@csateng.lab "cn=Angela.Garner,ou=UserAccounts,dc=csateng,dc=lab" -fn "Angela" -ln "Garner" -disabled no -display "Angela Garner" -desc "Facilities Facilities Manager" -office "DevLabs Facilities" -title "Facilities Manager" -company "DevLabs" -PWD "Badpass77813"
    DSADD user -upn Lynda.Bowman@csateng.lab "cn=Lynda.Bowman,ou=UserAccounts,dc=csateng,dc=lab" -fn "Lynda" -ln "Bowman" -disabled no -display "Lynda Bowman" -desc "IT Systems Support" -office "DevLabs IT" -title "Systems Support" -company "DevLabs" -PWD "Badpass28487"
    DSADD user -upn Kathleen.Delgado@csateng.lab "cn=Kathleen.Delgado,ou=UserAccounts,dc=csateng,dc=lab" -fn "Kathleen" -ln "Delgado" -disabled no -display "Kathleen Delgado" -desc "IT WebDev Marketer" -office "DevLabs IT" -title "WebDev Marketer" -company "DevLabs" -PWD "Badpass97825"
    DSADD user -upn Eileen.Moss@csateng.lab "cn=Eileen.Moss,ou=UserAccounts,dc=csateng,dc=lab" -fn "Eileen" -ln "Moss" -disabled no -display "Eileen Moss" -desc "BusAdmin Owner" -office "DevLabs BusAdmin" -title "Owner" -company "DevLabs" -PWD "Badpass51776"
    DSADD user -upn IT.Admin@csateng.lab "cn=IT.Admin,ou=UserAccounts,dc=csateng,dc=lab" -fn "IT" -ln "Admin" -disabled no -display "IT Admin" -desc "IT DEPARTMENT IT SUPERUSER ACCOUNT" -office "DevLabs IT DEPARTMENT" -title "IT SUPERUSER ACCOUNT" -company "DevLabs" -PWD "Badpass99999"
    DSADD user -upn Josefina.Robbins@csateng.lab "cn=Josefina.Robbins,ou=UserAccounts,dc=csateng,dc=lab" -fn "Josefina" -ln "Robbins" -disabled no -display "Josefina Robbins" -desc "Testing Grounds Of Intervening Epeirogenics Medical Physics Professor" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Medical Physics Professor" -company "DevLabs" -PWD "Badpass39351"
    DSADD user -upn Toni.Spencer@csateng.lab "cn=Toni.Spencer,ou=UserAccounts,dc=csateng,dc=lab" -fn "Toni" -ln "Spencer" -disabled no -display "Toni Spencer" -desc "Testing Grounds Of Intervening Epeirogenics Sterilization Technician" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Sterilization Technician" -company "DevLabs" -PWD "Badpass75041"
    DSADD user -upn Becky.Wise@csateng.lab "cn=Becky.Wise,ou=UserAccounts,dc=csateng,dc=lab" -fn "Becky" -ln "Wise" -disabled no -display "Becky Wise" -desc "Testing Grounds Of Intervening Epeirogenics Honest John Rocket Crew Member" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Honest John Rocket Crew Member" -company "DevLabs" -PWD "Badpass55039"
    DSADD user -upn Vicky.Hansen@csateng.lab "cn=Vicky.Hansen,ou=UserAccounts,dc=csateng,dc=lab" -fn "Vicky" -ln "Hansen" -disabled no -display "Vicky Hansen" -desc "Testing Grounds Of Intervening Epeirogenics PBX Operator" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "PBX Operator" -company "DevLabs" -PWD "Badpass1834"
    DSADD user -upn Juana.Fitzgerald@csateng.lab "cn=Juana.Fitzgerald,ou=UserAccounts,dc=csateng,dc=lab" -fn "Juana" -ln "Fitzgerald" -disabled no -display "Juana Fitzgerald" -desc "Testing Grounds Of Intervening Epeirogenics Field Map Technician" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Field Map Technician" -company "DevLabs" -PWD "Badpass18832"
    DSADD user -upn Judith.Green@csateng.lab "cn=Judith.Green,ou=UserAccounts,dc=csateng,dc=lab" -fn "Judith" -ln "Green" -disabled no -display "Judith Green" -desc "Testing Grounds Of Intervening Epeirogenics Combine Mechanic" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Combine Mechanic" -company "DevLabs" -PWD "Badpass91238"
    DSADD user -upn Drew.Simmons@csateng.lab "cn=Drew.Simmons,ou=UserAccounts,dc=csateng,dc=lab" -fn "Drew" -ln "Simmons" -disabled no -display "Drew Simmons" -desc "Testing Grounds Of Intervening Epeirogenics School Bus Driver" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "School Bus Driver" -company "DevLabs" -PWD "Badpass53349"
    DSADD user -upn Ernestine.Blake@csateng.lab "cn=Ernestine.Blake,ou=UserAccounts,dc=csateng,dc=lab" -fn "Ernestine" -ln "Blake" -disabled no -display "Ernestine Blake" -desc "Testing Grounds Of Intervening Epeirogenics Merchandise Displayer" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Merchandise Displayer" -company "DevLabs" -PWD "Badpass12790"
    DSADD user -upn Vickie.Ray@csateng.lab "cn=Vickie.Ray,ou=UserAccounts,dc=csateng,dc=lab" -fn "Vickie" -ln "Ray" -disabled no -display "Vickie Ray" -desc "Testing Grounds Of Intervening Epeirogenics National Association for Stock Car Auto Racing Driver" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "National Association for Stock Car Auto Racing Driver" -company "DevLabs" -PWD "Badpass62326"
    DSADD user -upn Jerry.Lawrence@csateng.lab "cn=Jerry.Lawrence,ou=UserAccounts,dc=csateng,dc=lab" -fn "Jerry" -ln "Lawrence" -disabled no -display "Jerry Lawrence" -desc "Test Center Of The Analysis Of Florigenics Independent Insurance Adjuster" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Independent Insurance Adjuster" -company "DevLabs" -PWD "Badpass55938"
    DSADD user -upn Darlene.Gibbs@csateng.lab "cn=Darlene.Gibbs,ou=UserAccounts,dc=csateng,dc=lab" -fn "Darlene" -ln "Gibbs" -disabled no -display "Darlene Gibbs" -desc "Test Center Of The Analysis Of Florigenics Electronic Warfare Specialist" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Electronic Warfare Specialist" -company "DevLabs" -PWD "Badpass46644"
    DSADD user -upn Jeremy.Willis@csateng.lab "cn=Jeremy.Willis,ou=UserAccounts,dc=csateng,dc=lab" -fn "Jeremy" -ln "Willis" -disabled no -display "Jeremy Willis" -desc "Test Center Of The Analysis Of Florigenics Administrative Court Justice" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Administrative Court Justice" -company "DevLabs" -PWD "Badpass86499"
    DSADD user -upn Kathy.Montgomery@csateng.lab "cn=Kathy.Montgomery,ou=UserAccounts,dc=csateng,dc=lab" -fn "Kathy" -ln "Montgomery" -disabled no -display "Kathy Montgomery" -desc "Test Center Of The Analysis Of Florigenics Prescription Clerk" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Prescription Clerk" -company "DevLabs" -PWD "Badpass89450"
    DSADD user -upn Veronica.Sparks@csateng.lab "cn=Veronica.Sparks,ou=UserAccounts,dc=csateng,dc=lab" -fn "Veronica" -ln "Sparks" -disabled no -display "Veronica Sparks" -desc "Test Center Of The Analysis Of Florigenics Guided Missile Launching System Maintenance Technician" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Guided Missile Launching System Maintenance Technician" -company "DevLabs" -PWD "Badpass22385"
    DSADD user -upn Bertha.Schultz@csateng.lab "cn=Bertha.Schultz,ou=UserAccounts,dc=csateng,dc=lab" -fn "Bertha" -ln "Schultz" -disabled no -display "Bertha Schultz" -desc "Test Center Of The Analysis Of Florigenics Staff Air Defense Officer" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Staff Air Defense Officer" -company "DevLabs" -PWD "Badpass90332"
    DSADD user -upn Judy.Bowen@csateng.lab "cn=Judy.Bowen,ou=UserAccounts,dc=csateng,dc=lab" -fn "Judy" -ln "Bowen" -disabled no -display "Judy Bowen" -desc "Test Center Of The Analysis Of Florigenics Film Process Operator" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Film Process Operator" -company "DevLabs" -PWD "Badpass76659"
    DSADD user -upn Candace.Martinez@csateng.lab "cn=Candace.Martinez,ou=UserAccounts,dc=csateng,dc=lab" -fn "Candace" -ln "Martinez" -disabled no -display "Candace Martinez" -desc "Test Center Of The Analysis Of Florigenics Aircraft Loadmaster Superintendent" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Aircraft Loadmaster Superintendent" -company "DevLabs" -PWD "Badpass83152"
    DSADD user -upn Everett.Watkins@csateng.lab "cn=Everett.Watkins,ou=UserAccounts,dc=csateng,dc=lab" -fn "Everett" -ln "Watkins" -disabled no -display "Everett Watkins" -desc "Defense Lab Of Obscure Transgenics Lay Health Advocate" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Lay Health Advocate" -company "DevLabs" -PWD "Badpass16102"
    DSADD user -upn Mandy.Rhodes@csateng.lab "cn=Mandy.Rhodes,ou=UserAccounts,dc=csateng,dc=lab" -fn "Mandy" -ln "Rhodes" -disabled no -display "Mandy Rhodes" -desc "Test Center Of Declined Ergogenics Geophysical Manager" -office "DevLabs Test Center Of Declined Ergogenics" -title "Geophysical Manager" -company "DevLabs" -PWD "Badpass31055"
    DSADD user -upn Gail.Kennedy@csateng.lab "cn=Gail.Kennedy,ou=UserAccounts,dc=csateng,dc=lab" -fn "Gail" -ln "Kennedy" -disabled no -display "Gail Kennedy" -desc "Defense Lab Of Obscure Transgenics Ship's Electronic Warfare Officer" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Ship's Electronic Warfare Officer" -company "DevLabs" -PWD "Badpass60705"
    DSADD user -upn Elmer.Wagner@csateng.lab "cn=Elmer.Wagner,ou=UserAccounts,dc=csateng,dc=lab" -fn "Elmer" -ln "Wagner" -disabled no -display "Elmer Wagner" -desc "Test Center Of Declined Ergogenics MIS Director" -office "DevLabs Test Center Of Declined Ergogenics" -title "MIS Director" -company "DevLabs" -PWD "Badpass7611"
    DSADD user -upn Angela.Hampton@csateng.lab "cn=Angela.Hampton,ou=UserAccounts,dc=csateng,dc=lab" -fn "Angela" -ln "Hampton" -disabled no -display "Angela Hampton" -desc "Defense Lab Of Obscure Transgenics Peer Health Promoter" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Peer Health Promoter" -company "DevLabs" -PWD "Badpass60044"
    DSADD user -upn Claire.Munoz@csateng.lab "cn=Claire.Munoz,ou=UserAccounts,dc=csateng,dc=lab" -fn "Claire" -ln "Munoz" -disabled no -display "Claire Munoz" -desc "Test Center Of Declined Ergogenics Secondary School Principal" -office "DevLabs Test Center Of Declined Ergogenics" -title "Secondary School Principal" -company "DevLabs" -PWD "Badpass11608"
    DSADD user -upn Joanna.Patton@csateng.lab "cn=Joanna.Patton,ou=UserAccounts,dc=csateng,dc=lab" -fn "Joanna" -ln "Patton" -disabled no -display "Joanna Patton" -desc "Defense Lab Of Obscure Transgenics Banquet Manager" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Banquet Manager" -company "DevLabs" -PWD "Badpass59451"
    DSADD user -upn Elaine.Carson@csateng.lab "cn=Elaine.Carson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Elaine" -ln "Carson" -disabled no -display "Elaine Carson" -desc "Test Center Of Declined Ergogenics Service Forester" -office "DevLabs Test Center Of Declined Ergogenics" -title "Service Forester" -company "DevLabs" -PWD "Badpass30285"
    DSADD user -upn Shelia.Osborne@csateng.lab "cn=Shelia.Osborne,ou=UserAccounts,dc=csateng,dc=lab" -fn "Shelia" -ln "Osborne" -disabled no -display "Shelia Osborne" -desc "Defense Lab Of Obscure Transgenics Computer Security Specialist" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Computer Security Specialist" -company "DevLabs" -PWD "Badpass46566"
    DSADD user -upn Alberto.Patterson@csateng.lab "cn=Alberto.Patterson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Alberto" -ln "Patterson" -disabled no -display "Alberto Patterson" -desc "Test Center Of Declined Ergogenics Computer Systems Security Analyst" -office "DevLabs Test Center Of Declined Ergogenics" -title "Computer Systems Security Analyst" -company "DevLabs" -PWD "Badpass31258"
    DSADD user -upn Bonnie.Barber@csateng.lab "cn=Bonnie.Barber,ou=UserAccounts,dc=csateng,dc=lab" -fn "Bonnie" -ln "Barber" -disabled no -display "Bonnie Barber" -desc "Defense Lab Of Obscure Transgenics Information Security Analyst" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Information Security Analyst" -company "DevLabs" -PWD "Badpass8383"
    DSADD user -upn Christian.Frazier@csateng.lab "cn=Christian.Frazier,ou=UserAccounts,dc=csateng,dc=lab" -fn "Christian" -ln "Frazier" -disabled no -display "Christian Frazier" -desc "Test Center Of Declined Ergogenics Information Systems Security Analyst" -office "DevLabs Test Center Of Declined Ergogenics" -title "Information Systems Security Analyst" -company "DevLabs" -PWD "Badpass85995"
    DSADD user -upn Cheryl.Ford@csateng.lab "cn=Cheryl.Ford,ou=UserAccounts,dc=csateng,dc=lab" -fn "Cheryl" -ln "Ford" -disabled no -display "Cheryl Ford" -desc "Test Center Of The Deterioration Of Palynology Internet Security Specialist" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Internet Security Specialist" -company "DevLabs" -PWD "Badpass42850"
    DSADD user -upn Leslie.Francis@csateng.lab "cn=Leslie.Francis,ou=UserAccounts,dc=csateng,dc=lab" -fn "Leslie" -ln "Francis" -disabled no -display "Leslie Francis" -desc "Test Center Of The Deterioration Of Palynology Network Security Analyst" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Network Security Analyst" -company "DevLabs" -PWD "Badpass79876"
    DSADD user -upn Dwight.Burns@csateng.lab "cn=Dwight.Burns,ou=UserAccounts,dc=csateng,dc=lab" -fn "Dwight" -ln "Burns" -disabled no -display "Dwight Burns" -desc "Test Center Of The Deterioration Of Palynology Applications Programmer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Applications Programmer" -company "DevLabs" -PWD "Badpass46592"
    DSADD user -upn Jill.Roberts@csateng.lab "cn=Jill.Roberts,ou=UserAccounts,dc=csateng,dc=lab" -fn "Jill" -ln "Roberts" -disabled no -display "Jill Roberts" -desc "Test Center Of The Deterioration Of Palynology Computer Language Coder" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Computer Language Coder" -company "DevLabs" -PWD "Badpass57759"
    DSADD user -upn Tamara.Armstrong@csateng.lab "cn=Tamara.Armstrong,ou=UserAccounts,dc=csateng,dc=lab" -fn "Tamara" -ln "Armstrong" -disabled no -display "Tamara Armstrong" -desc "Test Center Of The Deterioration Of Palynology Computer Programmer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Computer Programmer" -company "DevLabs" -PWD "Badpass32165"
    DSADD user -upn Lionel.Vaughn@csateng.lab "cn=Lionel.Vaughn,ou=UserAccounts,dc=csateng,dc=lab" -fn "Lionel" -ln "Vaughn" -disabled no -display "Lionel Vaughn" -desc "Test Center Of The Deterioration Of Palynology Junior Software Developer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Junior Software Developer" -company "DevLabs" -PWD "Badpass65184"
    DSADD user -upn Carmen.Chambers@csateng.lab "cn=Carmen.Chambers,ou=UserAccounts,dc=csateng,dc=lab" -fn "Carmen" -ln "Chambers" -disabled no -display "Carmen Chambers" -desc "Test Center Of The Deterioration Of Palynology Mainframe Programmer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Mainframe Programmer" -company "DevLabs" -PWD "Badpass31637"
    DSADD user -upn Taylor.Gill@csateng.lab "cn=Taylor.Gill,ou=UserAccounts,dc=csateng,dc=lab" -fn "Taylor" -ln "Gill" -disabled no -display "Taylor Gill" -desc "Test Center Of The Deterioration Of Palynology Systems Programmer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Systems Programmer" -company "DevLabs" -PWD "Badpass39026"
    DSADD user -upn Cora.Bowman@csateng.lab "cn=Cora.Bowman,ou=UserAccounts,dc=csateng,dc=lab" -fn "Cora" -ln "Bowman" -disabled no -display "Cora Bowman" -desc "Test Center Of The Deterioration Of Palynology Application Integration Engineer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Application Integration Engineer" -company "DevLabs" -PWD "Badpass87180"
    DSADD user -upn Virginia.Adkins@csateng.lab "cn=Virginia.Adkins,ou=UserAccounts,dc=csateng,dc=lab" -fn "Virginia" -ln "Adkins" -disabled no -display "Virginia Adkins" -desc "Test Center Of The Deterioration Of Palynology Applications Developer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Applications Developer" -company "DevLabs" -PWD "Badpass56388"
    DSADD user -upn Jody.Haynes@csateng.lab "cn=Jody.Haynes,ou=UserAccounts,dc=csateng,dc=lab" -fn "Jody" -ln "Haynes" -disabled no -display "Jody Haynes" -desc "Research Lab Of Mutating Garbology Computer Applications Developer" -office "DevLabs Research Lab Of Mutating Garbology" -title "Computer Applications Developer" -company "DevLabs" -PWD "Badpass59005"
    DSADD user -upn Corey.Quinn@csateng.lab "cn=Corey.Quinn,ou=UserAccounts,dc=csateng,dc=lab" -fn "Corey" -ln "Quinn" -disabled no -display "Corey Quinn" -desc "Research Lab Of Mutating Garbology Computer Applications Engineer" -office "DevLabs Research Lab Of Mutating Garbology" -title "Computer Applications Engineer" -company "DevLabs" -PWD "Badpass85030"
    DSADD user -upn Nancy.Yates@csateng.lab "cn=Nancy.Yates,ou=UserAccounts,dc=csateng,dc=lab" -fn "Nancy" -ln "Yates" -disabled no -display "Nancy Yates" -desc "Research Lab Of Mutating Garbology Database Developer" -office "DevLabs Research Lab Of Mutating Garbology" -title "Database Developer" -company "DevLabs" -PWD "Badpass43517"
    DSADD user -upn Eleanor.Olson@csateng.lab "cn=Eleanor.Olson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Eleanor" -ln "Olson" -disabled no -display "Eleanor Olson" -desc "Research Lab Of Mutating Garbology Software Applications Architect" -office "DevLabs Research Lab Of Mutating Garbology" -title "Software Applications Architect" -company "DevLabs" -PWD "Badpass74648"
    DSADD user -upn Shari.Hunt@csateng.lab "cn=Shari.Hunt,ou=UserAccounts,dc=csateng,dc=lab" -fn "Shari" -ln "Hunt" -disabled no -display "Shari Hunt" -desc "Research Lab Of Mutating Garbology Software Applications Designer" -office "DevLabs Research Lab Of Mutating Garbology" -title "Software Applications Designer" -company "DevLabs" -PWD "Badpass63423"
    DSADD user -upn Willie.Gonzales@csateng.lab "cn=Willie.Gonzales,ou=UserAccounts,dc=csateng,dc=lab" -fn "Willie" -ln "Gonzales" -disabled no -display "Willie Gonzales" -desc "Research Lab Of Mutating Garbology Software Applications Engineer" -office "DevLabs Research Lab Of Mutating Garbology" -title "Software Applications Engineer" -company "DevLabs" -PWD "Badpass57169"
    DSADD user -upn Rickey.Campbell@csateng.lab "cn=Rickey.Campbell,ou=UserAccounts,dc=csateng,dc=lab" -fn "Rickey" -ln "Campbell" -disabled no -display "Rickey Campbell" -desc "Research Lab Of Mutating Garbology Actuarial Associate" -office "DevLabs Research Lab Of Mutating Garbology" -title "Actuarial Associate" -company "DevLabs" -PWD "Badpass91838"
    DSADD user -upn Pablo.Goodman@csateng.lab "cn=Pablo.Goodman,ou=UserAccounts,dc=csateng,dc=lab" -fn "Pablo" -ln "Goodman" -disabled no -display "Pablo Goodman" -desc "Research Lab Of Mutating Garbology Actuarial Mathematician" -office "DevLabs Research Lab Of Mutating Garbology" -title "Actuarial Mathematician" -company "DevLabs" -PWD "Badpass71031"
    DSADD user -upn Maureen.Rios@csateng.lab "cn=Maureen.Rios,ou=UserAccounts,dc=csateng,dc=lab" -fn "Maureen" -ln "Rios" -disabled no -display "Maureen Rios" -desc "Defense Lab Of The Rectification Of Dysgenics Health Actuary" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Health Actuary" -company "DevLabs" -PWD "Badpass5877"
    DSADD user -upn Jim.Bailey@csateng.lab "cn=Jim.Bailey,ou=UserAccounts,dc=csateng,dc=lab" -fn "Jim" -ln "Bailey" -disabled no -display "Jim Bailey" -desc "Defense Lab Of The Rectification Of Dysgenics Insurance Actuary" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Insurance Actuary" -company "DevLabs" -PWD "Badpass13637"
    DSADD user -upn Debbie.Harrison@csateng.lab "cn=Debbie.Harrison,ou=UserAccounts,dc=csateng,dc=lab" -fn "Debbie" -ln "Harrison" -disabled no -display "Debbie Harrison" -desc "Defense Lab Of The Rectification Of Dysgenics Pricing Actuary" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Pricing Actuary" -company "DevLabs" -PWD "Badpass34971"
    DSADD user -upn Timmy.Richardson@csateng.lab "cn=Timmy.Richardson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Timmy" -ln "Richardson" -disabled no -display "Timmy Richardson" -desc "Defense Lab Of The Rectification Of Dysgenics Product Development Actuary" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Product Development Actuary" -company "DevLabs" -PWD "Badpass46037"
    DSADD user -upn Samantha.Ryan@csateng.lab "cn=Samantha.Ryan,ou=UserAccounts,dc=csateng,dc=lab" -fn "Samantha" -ln "Ryan" -disabled no -display "Samantha Ryan" -desc "Defense Lab Of The Rectification Of Dysgenics Operations Analyst" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Operations Analyst" -company "DevLabs" -PWD "Badpass5033"
    DSADD user -upn Roderick.Stone@csateng.lab "cn=Roderick.Stone,ou=UserAccounts,dc=csateng,dc=lab" -fn "Roderick" -ln "Stone" -disabled no -display "Roderick Stone" -desc "Defense Lab Of The Rectification Of Dysgenics Operations Research Analyst" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Operations Research Analyst" -company "DevLabs" -PWD "Badpass1984"
    DSADD user -upn Jackie.Hall@csateng.lab "cn=Jackie.Hall,ou=UserAccounts,dc=csateng,dc=lab" -fn "Jackie" -ln "Hall" -disabled no -display "Jackie Hall" -desc "Defense Lab Of The Rectification Of Dysgenics Procedure Analyst" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Procedure Analyst" -company "DevLabs" -PWD "Badpass62950"
    DSADD user -upn Sylvia.Mcgee@csateng.lab "cn=Sylvia.Mcgee,ou=UserAccounts,dc=csateng,dc=lab" -fn "Sylvia" -ln "Mcgee" -disabled no -display "Sylvia Mcgee" -desc "Defense Lab Of The Rectification Of Dysgenics Process Analyst" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Process Analyst" -company "DevLabs" -PWD "Badpass81222"
    DSADD user -upn Bernice.Lawson@csateng.lab "cn=Bernice.Lawson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Bernice" -ln "Lawson" -disabled no -display "Bernice Lawson" -desc "Defense Lab Of The Rectification Of Dysgenics Animal Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Animal Breeder" -company "DevLabs" -PWD "Badpass54618"
    DSADD user -upn Kyle.Owen@csateng.lab "cn=Kyle.Owen,ou=UserAccounts,dc=csateng,dc=lab" -fn "Kyle" -ln "Owen" -disabled no -display "Kyle Owen" -desc "Defense Lab Of The Rectification Of Dysgenics Cat Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Cat Breeder" -company "DevLabs" -PWD "Badpass64815"
    DSADD user -upn Orlando.Bennett@csateng.lab "cn=Orlando.Bennett,ou=UserAccounts,dc=csateng,dc=lab" -fn "Orlando" -ln "Bennett" -disabled no -display "Orlando Bennett" -desc "Defense Lab Of The Rectification Of Dysgenics Dairy Husbandry Worker" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Dairy Husbandry Worker" -company "DevLabs" -PWD "Badpass83275"
    DSADD user -upn Cindy.Vargas@csateng.lab "cn=Cindy.Vargas,ou=UserAccounts,dc=csateng,dc=lab" -fn "Cindy" -ln "Vargas" -disabled no -display "Cindy Vargas" -desc "Defense Lab Of The Rectification Of Dysgenics Dog Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Dog Breeder" -company "DevLabs" -PWD "Badpass73142"
    DSADD user -upn Geneva.Murphy@csateng.lab "cn=Geneva.Murphy,ou=UserAccounts,dc=csateng,dc=lab" -fn "Geneva" -ln "Murphy" -disabled no -display "Geneva Murphy" -desc "Defense Lab Of The Rectification Of Dysgenics Equine Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Equine Breeder" -company "DevLabs" -PWD "Badpass79401"
    DSADD user -upn Paula.Warner@csateng.lab "cn=Paula.Warner,ou=UserAccounts,dc=csateng,dc=lab" -fn "Paula" -ln "Warner" -disabled no -display "Paula Warner" -desc "Defense Lab Of The Rectification Of Dysgenics Horse Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Horse Breeder" -company "DevLabs" -PWD "Badpass78584"
    DSADD user -upn Felix.Ballard@csateng.lab "cn=Felix.Ballard,ou=UserAccounts,dc=csateng,dc=lab" -fn "Felix" -ln "Ballard" -disabled no -display "Felix Ballard" -desc "Defense Lab Of The Rectification Of Dysgenics Livestock Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Livestock Breeder" -company "DevLabs" -PWD "Badpass6354"
    DSADD user -upn Phyllis.Rivera@csateng.lab "cn=Phyllis.Rivera,ou=UserAccounts,dc=csateng,dc=lab" -fn "Phyllis" -ln "Rivera" -disabled no -display "Phyllis Rivera" -desc "Defense Lab Of The Rectification Of Dysgenics Poultry Inseminator" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Poultry Inseminator" -company "DevLabs" -PWD "Badpass82528"
    DSADD user -upn Harriet.Moss@csateng.lab "cn=Harriet.Moss,ou=UserAccounts,dc=csateng,dc=lab" -fn "Harriet" -ln "Moss" -disabled no -display "Harriet Moss" -desc "Defense Lab Of The Rectification Of Dysgenics Stallion Manager" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Stallion Manager" -company "DevLabs" -PWD "Badpass21525"
    DSADD user -upn Lucille.Tucker@csateng.lab "cn=Lucille.Tucker,ou=UserAccounts,dc=csateng,dc=lab" -fn "Lucille" -ln "Tucker" -disabled no -display "Lucille Tucker" -desc "Plutocratic Republic of Prefectures Rug Designer" -office "DevLabs Plutocratic Republic of Prefectures" -title "Rug Designer" -company "DevLabs" -PWD "Badpass7198"
    DSADD user -upn Oscar.Sherman@csateng.lab "cn=Oscar.Sherman,ou=UserAccounts,dc=csateng,dc=lab" -fn "Oscar" -ln "Sherman" -disabled no -display "Oscar Sherman" -desc "Plutocratic Republic of Prefectures Special Education Preschool Teacher" -office "DevLabs Plutocratic Republic of Prefectures" -title "Special Education Preschool Teacher" -company "DevLabs" -PWD "Badpass26745"
    DSADD user -upn Priscilla.Bryant@csateng.lab "cn=Priscilla.Bryant,ou=UserAccounts,dc=csateng,dc=lab" -fn "Priscilla" -ln "Bryant" -disabled no -display "Priscilla Bryant" -desc "Plutocratic Republic of Prefectures Radio Television Technical Director" -office "DevLabs Plutocratic Republic of Prefectures" -title "Radio Television Technical Director" -company "DevLabs" -PWD "Badpass37534"
    DSADD user -upn Gwendolyn.Berry@csateng.lab "cn=Gwendolyn.Berry,ou=UserAccounts,dc=csateng,dc=lab" -fn "Gwendolyn" -ln "Berry" -disabled no -display "Gwendolyn Berry" -desc "Plutocratic Republic of Prefectures Rail Signal Mechanic" -office "DevLabs Plutocratic Republic of Prefectures" -title "Rail Signal Mechanic" -company "DevLabs" -PWD "Badpass16263"
    DSADD user -upn Cynthia.Mcdonald@csateng.lab "cn=Cynthia.Mcdonald,ou=UserAccounts,dc=csateng,dc=lab" -fn "Cynthia" -ln "Mcdonald" -disabled no -display "Cynthia Mcdonald" -desc "Plutocratic Republic of Prefectures Funeral Arrangement Director" -office "DevLabs Plutocratic Republic of Prefectures" -title "Funeral Arrangement Director" -company "DevLabs" -PWD "Badpass67127"
    DSADD user -upn Ignacio.Long@csateng.lab "cn=Ignacio.Long,ou=UserAccounts,dc=csateng,dc=lab" -fn "Ignacio" -ln "Long" -disabled no -display "Ignacio Long" -desc "Plutocratic Republic of Prefectures Tool Room Supervisor" -office "DevLabs Plutocratic Republic of Prefectures" -title "Tool Room Supervisor" -company "DevLabs" -PWD "Badpass59735"
    DSADD user -upn Patsy.Medina@csateng.lab "cn=Patsy.Medina,ou=UserAccounts,dc=csateng,dc=lab" -fn "Patsy" -ln "Medina" -disabled no -display "Patsy Medina" -desc "Plutocratic Republic of Prefectures Non-Acoustic Operator" -office "DevLabs Plutocratic Republic of Prefectures" -title "Non-Acoustic Operator" -company "DevLabs" -PWD "Badpass58883"
    DSADD user -upn Spencer.Watts@csateng.lab "cn=Spencer.Watts,ou=UserAccounts,dc=csateng,dc=lab" -fn "Spencer" -ln "Watts" -disabled no -display "Spencer Watts" -desc "Plutocratic Republic of Prefectures Foundry Molder" -office "DevLabs Plutocratic Republic of Prefectures" -title "Foundry Molder" -company "DevLabs" -PWD "Badpass11676"
    DSADD user -upn Stuart.Poole@csateng.lab "cn=Stuart.Poole,ou=UserAccounts,dc=csateng,dc=lab" -fn "Stuart" -ln "Poole" -disabled no -display "Stuart Poole" -desc "Plutocratic Republic of Prefectures Coal Tram Driver" -office "DevLabs Plutocratic Republic of Prefectures" -title "Coal Tram Driver" -company "DevLabs" -PWD "Badpass68767"
    DSADD user -upn Dana.Horton@csateng.lab "cn=Dana.Horton,ou=UserAccounts,dc=csateng,dc=lab" -fn "Dana" -ln "Horton" -disabled no -display "Dana Horton" -desc "Plutocratic Republic of Prefectures Cage Cashier" -office "DevLabs Plutocratic Republic of Prefectures" -title "Cage Cashier" -company "DevLabs" -PWD "Badpass89692"
    DSADD user -upn Luz.Boone@csateng.lab "cn=Luz.Boone,ou=UserAccounts,dc=csateng,dc=lab" -fn "Luz" -ln "Boone" -disabled no -display "Luz Boone" -desc "Plutocratic Republic of Prefectures Golf Course Laborer" -office "DevLabs Plutocratic Republic of Prefectures" -title "Golf Course Laborer" -company "DevLabs" -PWD "Badpass6850"
    DSADD user -upn Diane.Sims@csateng.lab "cn=Diane.Sims,ou=UserAccounts,dc=csateng,dc=lab" -fn "Diane" -ln "Sims" -disabled no -display "Diane Sims" -desc "Plutocratic Republic of Prefectures Aegis Console Operator Track 3" -office "DevLabs Plutocratic Republic of Prefectures" -title "Aegis Console Operator Track 3" -company "DevLabs" -PWD "Badpass10158"
    DSADD user -upn Joanne.Stewart@csateng.lab "cn=Joanne.Stewart,ou=UserAccounts,dc=csateng,dc=lab" -fn "Joanne" -ln "Stewart" -disabled no -display "Joanne Stewart" -desc "Plutocratic Republic of Prefectures Dairy Husbandry Worker" -office "DevLabs Plutocratic Republic of Prefectures" -title "Dairy Husbandry Worker" -company "DevLabs" -PWD "Badpass19993"
    DSADD user -upn Wallace.West@csateng.lab "cn=Wallace.West,ou=UserAccounts,dc=csateng,dc=lab" -fn "Wallace" -ln "West" -disabled no -display "Wallace West" -desc "Plutocratic Republic of Prefectures Airborne Mission Systems Superintendent" -office "DevLabs Plutocratic Republic of Prefectures" -title "Airborne Mission Systems Superintendent" -company "DevLabs" -PWD "Badpass61788"
    DSADD user -upn Nellie.Higgins@csateng.lab "cn=Nellie.Higgins,ou=UserAccounts,dc=csateng,dc=lab" -fn "Nellie" -ln "Higgins" -disabled no -display "Nellie Higgins" -desc "Plutocratic Republic of Prefectures An/Sqq-32(V)3 Minehunting Sonar Set Operator (Mss)" -office "DevLabs Plutocratic Republic of Prefectures" -title "An/Sqq-32(V)3 Minehunting Sonar Set Operator (Mss)" -company "DevLabs" -PWD "Badpass85310"
    DSADD user -upn Gabriel.Roberson@csateng.lab "cn=Gabriel.Roberson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Gabriel" -ln "Roberson" -disabled no -display "Gabriel Roberson" -desc "Plutocratic Republic of Prefectures Certified Mortician" -office "DevLabs Plutocratic Republic of Prefectures" -title "Certified Mortician" -company "DevLabs" -PWD "Badpass61561"
    DSADD user -upn Roberto.Lyons@csateng.lab "cn=Roberto.Lyons,ou=UserAccounts,dc=csateng,dc=lab" -fn "Roberto" -ln "Lyons" -disabled no -display "Roberto Lyons" -desc "The Light Academy National Association for Stock Car Auto Racing Driver" -office "DevLabs The Light Academy" -title "National Association for Stock Car Auto Racing Driver" -company "DevLabs" -PWD "Badpass52164"
    DSADD user -upn Beverly.Lucas@csateng.lab "cn=Beverly.Lucas,ou=UserAccounts,dc=csateng,dc=lab" -fn "Beverly" -ln "Lucas" -disabled no -display "Beverly Lucas" -desc "The Light Academy Souvenir Street Vendor" -office "DevLabs The Light Academy" -title "Souvenir Street Vendor" -company "DevLabs" -PWD "Badpass1874"
    DSADD user -upn Dorothy.Pearson@csateng.lab "cn=Dorothy.Pearson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Dorothy" -ln "Pearson" -disabled no -display "Dorothy Pearson" -desc "The Light Academy Conductor" -office "DevLabs The Light Academy" -title "Conductor" -company "DevLabs" -PWD "Badpass76416"
    DSADD user -upn Glen.Shaw@csateng.lab "cn=Glen.Shaw,ou=UserAccounts,dc=csateng,dc=lab" -fn "Glen" -ln "Shaw" -disabled no -display "Glen Shaw" -desc "The Light Academy Meter Maid" -office "DevLabs The Light Academy" -title "Meter Maid" -company "DevLabs" -PWD "Badpass17321"
    DSADD user -upn Ginger.Wilkins@csateng.lab "cn=Ginger.Wilkins,ou=UserAccounts,dc=csateng,dc=lab" -fn "Ginger" -ln "Wilkins" -disabled no -display "Ginger Wilkins" -desc "The Light Academy Victorian Literature Professor" -office "DevLabs The Light Academy" -title "Victorian Literature Professor" -company "DevLabs" -PWD "Badpass56275"
    DSADD user -upn Leona.Wallace@csateng.lab "cn=Leona.Wallace,ou=UserAccounts,dc=csateng,dc=lab" -fn "Leona" -ln "Wallace" -disabled no -display "Leona Wallace" -desc "The Light Academy Deck Cadet" -office "DevLabs The Light Academy" -title "Deck Cadet" -company "DevLabs" -PWD "Badpass80651"
    DSADD user -upn Chester.Dean@csateng.lab "cn=Chester.Dean,ou=UserAccounts,dc=csateng,dc=lab" -fn "Chester" -ln "Dean" -disabled no -display "Chester Dean" -desc "The Light Academy Objects Conservator" -office "DevLabs The Light Academy" -title "Objects Conservator" -company "DevLabs" -PWD "Badpass21023"
    DSADD user -upn Rosalie.Torres@csateng.lab "cn=Rosalie.Torres,ou=UserAccounts,dc=csateng,dc=lab" -fn "Rosalie" -ln "Torres" -disabled no -display "Rosalie Torres" -desc "The Light Academy Naval Aircrewman Avionics" -office "DevLabs The Light Academy" -title "Naval Aircrewman Avionics" -company "DevLabs" -PWD "Badpass62974"
    DSADD user -upn Gerardo.Ross@csateng.lab "cn=Gerardo.Ross,ou=UserAccounts,dc=csateng,dc=lab" -fn "Gerardo" -ln "Ross" -disabled no -display "Gerardo Ross" -desc "The Light Academy Real Estate Loan Officer" -office "DevLabs The Light Academy" -title "Real Estate Loan Officer" -company "DevLabs" -PWD "Badpass97522"
    DSADD user -upn Charlene.Shelton@csateng.lab "cn=Charlene.Shelton,ou=UserAccounts,dc=csateng,dc=lab" -fn "Charlene" -ln "Shelton" -disabled no -display "Charlene Shelton" -desc "The Light Academy Pipe Fitter" -office "DevLabs The Light Academy" -title "Pipe Fitter" -company "DevLabs" -PWD "Badpass47743"
    DSADD user -upn Joyce.Jefferson@csateng.lab "cn=Joyce.Jefferson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Joyce" -ln "Jefferson" -disabled no -display "Joyce Jefferson" -desc "Integrated Gyrohands Television Repairer" -office "DevLabs Integrated Gyrohands" -title "Television Repairer" -company "DevLabs" -PWD "Badpass4557"
    DSADD user -upn Damon.Rodriguez@csateng.lab "cn=Damon.Rodriguez,ou=UserAccounts,dc=csateng,dc=lab" -fn "Damon" -ln "Rodriguez" -disabled no -display "Damon Rodriguez" -desc "Protonic Distortion Wardrobe Custodian" -office "DevLabs Protonic Distortion" -title "Wardrobe Custodian" -company "DevLabs" -PWD "Badpass82446"
    DSADD user -upn Oliver.Barton@csateng.lab "cn=Oliver.Barton,ou=UserAccounts,dc=csateng,dc=lab" -fn "Oliver" -ln "Barton" -disabled no -display "Oliver Barton" -desc "Office of Programming Troubleshooting and Application Security Highway Inspector" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Highway Inspector" -company "DevLabs" -PWD "Badpass10237"
    DSADD user -upn Janis.Sutton@csateng.lab "cn=Janis.Sutton,ou=UserAccounts,dc=csateng,dc=lab" -fn "Janis" -ln "Sutton" -disabled no -display "Janis Sutton" -desc "Office of Programming Troubleshooting and Application Security Mortgage Closing Clerk" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Mortgage Closing Clerk" -company "DevLabs" -PWD "Badpass48899"
    DSADD user -upn Paul.Moran@csateng.lab "cn=Paul.Moran,ou=UserAccounts,dc=csateng,dc=lab" -fn "Paul" -ln "Moran" -disabled no -display "Paul Moran" -desc "Office of Programming Troubleshooting and Application Security Journalism Professor" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Journalism Professor" -company "DevLabs" -PWD "Badpass55810"
    DSADD user -upn Enrique.Gomez@csateng.lab "cn=Enrique.Gomez,ou=UserAccounts,dc=csateng,dc=lab" -fn "Enrique" -ln "Gomez" -disabled no -display "Enrique Gomez" -desc "Office of Programming Troubleshooting and Application Security Vacuum Cleaner Repair Person" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Vacuum Cleaner Repair Person" -company "DevLabs" -PWD "Badpass71668"
    DSADD user -upn Walter.Cannon@csateng.lab "cn=Walter.Cannon,ou=UserAccounts,dc=csateng,dc=lab" -fn "Walter" -ln "Cannon" -disabled no -display "Walter Cannon" -desc "Office of Programming Troubleshooting and Application Security Paddock Judge" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Paddock Judge" -company "DevLabs" -PWD "Badpass61960"
    DSADD user -upn Antonio.Garza@csateng.lab "cn=Antonio.Garza,ou=UserAccounts,dc=csateng,dc=lab" -fn "Antonio" -ln "Garza" -disabled no -display "Antonio Garza" -desc "Office of Programming Troubleshooting and Application Security Aviation Ordnance Officer" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Aviation Ordnance Officer" -company "DevLabs" -PWD "Badpass5241"
    DSADD user -upn Kent.Sullivan@csateng.lab "cn=Kent.Sullivan,ou=UserAccounts,dc=csateng,dc=lab" -fn "Kent" -ln "Sullivan" -disabled no -display "Kent Sullivan" -desc "Office of Programming Troubleshooting and Application Security Career Technical Counselor" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Career Technical Counselor" -company "DevLabs" -PWD "Badpass17022"
    DSADD user -upn Sonia.Griffith@csateng.lab "cn=Sonia.Griffith,ou=UserAccounts,dc=csateng,dc=lab" -fn "Sonia" -ln "Griffith" -disabled no -display "Sonia Griffith" -desc "Office of Programming Troubleshooting and Application Security Maxillofacial Prosthodontist" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Maxillofacial Prosthodontist" -company "DevLabs" -PWD "Badpass11371"
    DSADD user -upn Jean.Ross@csateng.lab "cn=Jean.Ross,ou=UserAccounts,dc=csateng,dc=lab" -fn "Jean" -ln "Ross" -disabled no -display "Jean Ross" -desc "Office of Programming Troubleshooting and Application Security Stoker Installer" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Stoker Installer" -company "DevLabs" -PWD "Badpass15372"
    DSADD user -upn Kerry.Byrd@csateng.lab "cn=Kerry.Byrd,ou=UserAccounts,dc=csateng,dc=lab" -fn "Kerry" -ln "Byrd" -disabled no -display "Kerry Byrd" -desc "Office of Programming Troubleshooting and Application Security Billiard Player" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Billiard Player" -company "DevLabs" -PWD "Badpass73384"
    DSADD user -upn Wallace.Watson@csateng.lab "cn=Wallace.Watson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Wallace" -ln "Watson" -disabled no -display "Wallace Watson" -desc "PC Troubleshooting Branch Foreign Exchange Position Clerk" -office "DevLabs PC Troubleshooting Branch" -title "Foreign Exchange Position Clerk" -company "DevLabs" -PWD "Badpass37450"
    DSADD user -upn Jill.Campbell@csateng.lab "cn=Jill.Campbell,ou=UserAccounts,dc=csateng,dc=lab" -fn "Jill" -ln "Campbell" -disabled no -display "Jill Campbell" -desc "PC Troubleshooting Branch Estate Conservator" -office "DevLabs PC Troubleshooting Branch" -title "Estate Conservator" -company "DevLabs" -PWD "Badpass25598"
    DSADD user -upn Regina.Neal@csateng.lab "cn=Regina.Neal,ou=UserAccounts,dc=csateng,dc=lab" -fn "Regina" -ln "Neal" -disabled no -display "Regina Neal" -desc "PC Troubleshooting Branch Mortgage Accounting Clerk" -office "DevLabs PC Troubleshooting Branch" -title "Mortgage Accounting Clerk" -company "DevLabs" -PWD "Badpass38541"
    DSADD user -upn Vanessa.Floyd@csateng.lab "cn=Vanessa.Floyd,ou=UserAccounts,dc=csateng,dc=lab" -fn "Vanessa" -ln "Floyd" -disabled no -display "Vanessa Floyd" -desc "PC Troubleshooting Branch Economic Geographer" -office "DevLabs PC Troubleshooting Branch" -title "Economic Geographer" -company "DevLabs" -PWD "Badpass82092"
    DSADD user -upn Essie.Mclaughlin@csateng.lab "cn=Essie.Mclaughlin,ou=UserAccounts,dc=csateng,dc=lab" -fn "Essie" -ln "Mclaughlin" -disabled no -display "Essie Mclaughlin" -desc "PC Troubleshooting Branch Head Greenskeeper" -office "DevLabs PC Troubleshooting Branch" -title "Head Greenskeeper" -company "DevLabs" -PWD "Badpass30530"
    DSADD user -upn Dana.Johnson@csateng.lab "cn=Dana.Johnson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Dana" -ln "Johnson" -disabled no -display "Dana Johnson" -desc "PC Troubleshooting Branch Public Affairs Officer" -office "DevLabs PC Troubleshooting Branch" -title "Public Affairs Officer" -company "DevLabs" -PWD "Badpass41884"
    DSADD user -upn Mona.Ballard@csateng.lab "cn=Mona.Ballard,ou=UserAccounts,dc=csateng,dc=lab" -fn "Mona" -ln "Ballard" -disabled no -display "Mona Ballard" -desc "PC Troubleshooting Branch Manufacturing Engineering Professor" -office "DevLabs PC Troubleshooting Branch" -title "Manufacturing Engineering Professor" -company "DevLabs" -PWD "Badpass82899"
    DSADD user -upn Santiago.Parks@csateng.lab "cn=Santiago.Parks,ou=UserAccounts,dc=csateng,dc=lab" -fn "Santiago" -ln "Parks" -disabled no -display "Santiago Parks" -desc "PC Troubleshooting Branch Drug Abuse Counselor" -office "DevLabs PC Troubleshooting Branch" -title "Drug Abuse Counselor" -company "DevLabs" -PWD "Badpass67974"
    DSADD user -upn Cristina.Page@csateng.lab "cn=Cristina.Page,ou=UserAccounts,dc=csateng,dc=lab" -fn "Cristina" -ln "Page" -disabled no -display "Cristina Page" -desc "PC Troubleshooting Branch Airborne Operations Manager" -office "DevLabs PC Troubleshooting Branch" -title "Airborne Operations Manager" -company "DevLabs" -PWD "Badpass4564"
    DSADD user -upn Harvey.Brady@csateng.lab "cn=Harvey.Brady,ou=UserAccounts,dc=csateng,dc=lab" -fn "Harvey" -ln "Brady" -disabled no -display "Harvey Brady" -desc "PC Troubleshooting Branch Florist" -office "DevLabs PC Troubleshooting Branch" -title "Florist" -company "DevLabs" -PWD "Badpass98763"
    DSADD user -upn Grace.Turner@csateng.lab "cn=Grace.Turner,ou=UserAccounts,dc=csateng,dc=lab" -fn "Grace" -ln "Turner" -disabled no -display "Grace Turner" -desc "Agency of Portable PC Implementation Stage Electrician" -office "DevLabs Agency of Portable PC Implementation" -title "Stage Electrician" -company "DevLabs" -PWD "Badpass79900"
    DSADD user -upn Katie.Maxwell@csateng.lab "cn=Katie.Maxwell,ou=UserAccounts,dc=csateng,dc=lab" -fn "Katie" -ln "Maxwell" -disabled no -display "Katie Maxwell" -desc "Agency of Portable PC Implementation Bilingual Kindergarten Teacher" -office "DevLabs Agency of Portable PC Implementation" -title "Bilingual Kindergarten Teacher" -company "DevLabs" -PWD "Badpass23686"
    DSADD user -upn Don.Potter@csateng.lab "cn=Don.Potter,ou=UserAccounts,dc=csateng,dc=lab" -fn "Don" -ln "Potter" -disabled no -display "Don Potter" -desc "Agency of Portable PC Implementation Construction Ironworker Helper" -office "DevLabs Agency of Portable PC Implementation" -title "Construction Ironworker Helper" -company "DevLabs" -PWD "Badpass82814"
    DSADD user -upn Loren.Elliott@csateng.lab "cn=Loren.Elliott,ou=UserAccounts,dc=csateng,dc=lab" -fn "Loren" -ln "Elliott" -disabled no -display "Loren Elliott" -desc "Agency of Portable PC Implementation Visual Merchandiser" -office "DevLabs Agency of Portable PC Implementation" -title "Visual Merchandiser" -company "DevLabs" -PWD "Badpass11447"
    DSADD user -upn Marcia.Fitzgerald@csateng.lab "cn=Marcia.Fitzgerald,ou=UserAccounts,dc=csateng,dc=lab" -fn "Marcia" -ln "Fitzgerald" -disabled no -display "Marcia Fitzgerald" -desc "Agency of Portable PC Implementation Telesales Supervisor" -office "DevLabs Agency of Portable PC Implementation" -title "Telesales Supervisor" -company "DevLabs" -PWD "Badpass88006"
    DSADD user -upn Sylvia.Sutton@csateng.lab "cn=Sylvia.Sutton,ou=UserAccounts,dc=csateng,dc=lab" -fn "Sylvia" -ln "Sutton" -disabled no -display "Sylvia Sutton" -desc "Agency of Portable PC Implementation Fire Control Officer" -office "DevLabs Agency of Portable PC Implementation" -title "Fire Control Officer" -company "DevLabs" -PWD "Badpass11813"
    DSADD user -upn Rosemary.Peterson@csateng.lab "cn=Rosemary.Peterson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Rosemary" -ln "Peterson" -disabled no -display "Rosemary Peterson" -desc "Code Security and PC Technology Team Cement Truck Driver" -office "DevLabs Code Security and PC Technology Team" -title "Cement Truck Driver" -company "DevLabs" -PWD "Badpass44039"
    DSADD user -upn Anthony.Caldwell@csateng.lab "cn=Anthony.Caldwell,ou=UserAccounts,dc=csateng,dc=lab" -fn "Anthony" -ln "Caldwell" -disabled no -display "Anthony Caldwell" -desc "Code Security and PC Technology Team Window Cleaner" -office "DevLabs Code Security and PC Technology Team" -title "Window Cleaner" -company "DevLabs" -PWD "Badpass78369"
    DSADD user -upn Brooke.Webster@csateng.lab "cn=Brooke.Webster,ou=UserAccounts,dc=csateng,dc=lab" -fn "Brooke" -ln "Webster" -disabled no -display "Brooke Webster" -desc "Code Security and PC Technology Team Licensed Clinical Mental Health Counselor" -office "DevLabs Code Security and PC Technology Team" -title "Licensed Clinical Mental Health Counselor" -company "DevLabs" -PWD "Badpass22968"
    DSADD user -upn Penny.Gregory@csateng.lab "cn=Penny.Gregory,ou=UserAccounts,dc=csateng,dc=lab" -fn "Penny" -ln "Gregory" -disabled no -display "Penny Gregory" -desc "Code Security and PC Technology Team Store Gift Wrap Associate" -office "DevLabs Code Security and PC Technology Team" -title "Store Gift Wrap Associate" -company "DevLabs" -PWD "Badpass29522"
    DSADD user -upn Dominic.Mendoza@csateng.lab "cn=Dominic.Mendoza,ou=UserAccounts,dc=csateng,dc=lab" -fn "Dominic" -ln "Mendoza" -disabled no -display "Dominic Mendoza" -desc "Code Security and PC Technology Team Traveling Missionary" -office "DevLabs Code Security and PC Technology Team" -title "Traveling Missionary" -company "DevLabs" -PWD "Badpass45551"
    DSADD user -upn Ethel.Bishop@csateng.lab "cn=Ethel.Bishop,ou=UserAccounts,dc=csateng,dc=lab" -fn "Ethel" -ln "Bishop" -disabled no -display "Ethel Bishop" -desc "Code Security and PC Technology Team Tax Compliance Representative" -office "DevLabs Code Security and PC Technology Team" -title "Tax Compliance Representative" -company "DevLabs" -PWD "Badpass14715"
    DSADD user -upn Kelvin.Ortiz@csateng.lab "cn=Kelvin.Ortiz,ou=UserAccounts,dc=csateng,dc=lab" -fn "Kelvin" -ln "Ortiz" -disabled no -display "Kelvin Ortiz" -desc "Code Security and PC Technology Team Hotel Baggage Handler" -office "DevLabs Code Security and PC Technology Team" -title "Hotel Baggage Handler" -company "DevLabs" -PWD "Badpass73993"
    DSADD user -upn Caleb.Kennedy@csateng.lab "cn=Caleb.Kennedy,ou=UserAccounts,dc=csateng,dc=lab" -fn "Caleb" -ln "Kennedy" -disabled no -display "Caleb Kennedy" -desc "Code Security and PC Technology Team Registered Medical Transcriptionist" -office "DevLabs Code Security and PC Technology Team" -title "Registered Medical Transcriptionist" -company "DevLabs" -PWD "Badpass76530"
    DSADD user -upn Randal.Parsons@csateng.lab "cn=Randal.Parsons,ou=UserAccounts,dc=csateng,dc=lab" -fn "Randal" -ln "Parsons" -disabled no -display "Randal Parsons" -desc "Code Security and PC Technology Team Pugilist" -office "DevLabs Code Security and PC Technology Team" -title "Pugilist" -company "DevLabs" -PWD "Badpass11028"
    DSADD user -upn Seth.Harper@csateng.lab "cn=Seth.Harper,ou=UserAccounts,dc=csateng,dc=lab" -fn "Seth" -ln "Harper" -disabled no -display "Seth Harper" -desc "Code Security and PC Technology Team Wholesale Ultrasonic Equipment Salesperson" -office "DevLabs Code Security and PC Technology Team" -title "Wholesale Ultrasonic Equipment Salesperson" -company "DevLabs" -PWD "Badpass74210"
    DSADD user -upn Debra.Thornton@csateng.lab "cn=Debra.Thornton,ou=UserAccounts,dc=csateng,dc=lab" -fn "Debra" -ln "Thornton" -disabled no -display "Debra Thornton" -desc "Illuminated Technocracy Sports Complex Attendant" -office "DevLabs Illuminated Technocracy" -title "Sports Complex Attendant" -company "DevLabs" -PWD "Badpass84977"
    DSADD user -upn Jessie.Schmidt@csateng.lab "cn=Jessie.Schmidt,ou=UserAccounts,dc=csateng,dc=lab" -fn "Jessie" -ln "Schmidt" -disabled no -display "Jessie Schmidt" -desc "Illuminated Technocracy Boiler Operator" -office "DevLabs Illuminated Technocracy" -title "Boiler Operator" -company "DevLabs" -PWD "Badpass44945"
    DSADD user -upn Antoinette.Morrison@csateng.lab "cn=Antoinette.Morrison,ou=UserAccounts,dc=csateng,dc=lab" -fn "Antoinette" -ln "Morrison" -disabled no -display "Antoinette Morrison" -desc "Illuminated Technocracy Booking Manager" -office "DevLabs Illuminated Technocracy" -title "Booking Manager" -company "DevLabs" -PWD "Badpass96146"
    DSADD user -upn Mark.Mccormick@csateng.lab "cn=Mark.Mccormick,ou=UserAccounts,dc=csateng,dc=lab" -fn "Mark" -ln "Mccormick" -disabled no -display "Mark Mccormick" -desc "Illuminated Technocracy Registered Medical Transcriptionist" -office "DevLabs Illuminated Technocracy" -title "Registered Medical Transcriptionist" -company "DevLabs" -PWD "Badpass43688"
    DSADD user -upn Jeanette.Wise@csateng.lab "cn=Jeanette.Wise,ou=UserAccounts,dc=csateng,dc=lab" -fn "Jeanette" -ln "Wise" -disabled no -display "Jeanette Wise" -desc "Illuminated Technocracy Tape Editor" -office "DevLabs Illuminated Technocracy" -title "Tape Editor" -company "DevLabs" -PWD "Badpass56301"
    DSADD user -upn Elena.Hernandez@csateng.lab "cn=Elena.Hernandez,ou=UserAccounts,dc=csateng,dc=lab" -fn "Elena" -ln "Hernandez" -disabled no -display "Elena Hernandez" -desc "Illuminated Technocracy Cotton Ginner" -office "DevLabs Illuminated Technocracy" -title "Cotton Ginner" -company "DevLabs" -PWD "Badpass95861"
    DSADD user -upn Bob.King@csateng.lab "cn=Bob.King,ou=UserAccounts,dc=csateng,dc=lab" -fn "Bob" -ln "King" -disabled no -display "Bob King" -desc "Radioactive Team Glacier Music Adapter" -office "DevLabs Radioactive Team Glacier" -title "Music Adapter" -company "DevLabs" -PWD "Badpass46339"
    DSADD user -upn Vera.Daniels@csateng.lab "cn=Vera.Daniels,ou=UserAccounts,dc=csateng,dc=lab" -fn "Vera" -ln "Daniels" -disabled no -display "Vera Daniels" -desc "Radioactive Team Glacier Poultry Inseminator" -office "DevLabs Radioactive Team Glacier" -title "Poultry Inseminator" -company "DevLabs" -PWD "Badpass78347"
    DSADD user -upn Colleen.Blair@csateng.lab "cn=Colleen.Blair,ou=UserAccounts,dc=csateng,dc=lab" -fn "Colleen" -ln "Blair" -disabled no -display "Colleen Blair" -desc "Radioactive Team Glacier DTR" -office "DevLabs Radioactive Team Glacier" -title "DTR" -company "DevLabs" -PWD "Badpass19252"
    DSADD user -upn Arlene.Poole@csateng.lab "cn=Arlene.Poole,ou=UserAccounts,dc=csateng,dc=lab" -fn "Arlene" -ln "Poole" -disabled no -display "Arlene Poole" -desc "Radioactive Team Glacier Songwriter" -office "DevLabs Radioactive Team Glacier" -title "Songwriter" -company "DevLabs" -PWD "Badpass78687"
    DSADD user -upn Stella.Palmer@csateng.lab "cn=Stella.Palmer,ou=UserAccounts,dc=csateng,dc=lab" -fn "Stella" -ln "Palmer" -disabled no -display "Stella Palmer" -desc "Radioactive Team Glacier Bicycle Racer" -office "DevLabs Radioactive Team Glacier" -title "Bicycle Racer" -company "DevLabs" -PWD "Badpass77917"
    DSADD user -upn Phil.Hogan@csateng.lab "cn=Phil.Hogan,ou=UserAccounts,dc=csateng,dc=lab" -fn "Phil" -ln "Hogan" -disabled no -display "Phil Hogan" -desc "Radioactive Team Glacier Certified Nurse Midwife (CNM)" -office "DevLabs Radioactive Team Glacier" -title "Certified Nurse Midwife (CNM)" -company "DevLabs" -PWD "Badpass69445"
    DSADD user -upn Angelo.Richards@csateng.lab "cn=Angelo.Richards,ou=UserAccounts,dc=csateng,dc=lab" -fn "Angelo" -ln "Richards" -disabled no -display "Angelo Richards" -desc "Radioactive Team Glacier Field Enumerator" -office "DevLabs Radioactive Team Glacier" -title "Field Enumerator" -company "DevLabs" -PWD "Badpass97334"
    DSADD user -upn Jasmine.Lawson@csateng.lab "cn=Jasmine.Lawson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Jasmine" -ln "Lawson" -disabled no -display "Jasmine Lawson" -desc "Radioactive Team Glacier Industrial Photographer" -office "DevLabs Radioactive Team Glacier" -title "Industrial Photographer" -company "DevLabs" -PWD "Badpass30977"
    DSADD user -upn Julio.Davis@csateng.lab "cn=Julio.Davis,ou=UserAccounts,dc=csateng,dc=lab" -fn "Julio" -ln "Davis" -disabled no -display "Julio Davis" -desc "Radioactive Team Glacier Early Childhood Special Education Teacher" -office "DevLabs Radioactive Team Glacier" -title "Early Childhood Special Education Teacher" -company "DevLabs" -PWD "Badpass46270"
    DSADD user -upn Monique.Price@csateng.lab "cn=Monique.Price,ou=UserAccounts,dc=csateng,dc=lab" -fn "Monique" -ln "Price" -disabled no -display "Monique Price" -desc "Radioactive Team Glacier Telephone Interviewer" -office "DevLabs Radioactive Team Glacier" -title "Telephone Interviewer" -company "DevLabs" -PWD "Badpass788"
    DSADD user -upn Gerardo.Lindsey@csateng.lab "cn=Gerardo.Lindsey,ou=UserAccounts,dc=csateng,dc=lab" -fn "Gerardo" -ln "Lindsey" -disabled no -display "Gerardo Lindsey" -desc "Radioactive Team Glacier Adult Nurse Practitioner" -office "DevLabs Radioactive Team Glacier" -title "Adult Nurse Practitioner" -company "DevLabs" -PWD "Badpass96589"
    DSADD user -upn Terrence.Chapman@csateng.lab "cn=Terrence.Chapman,ou=UserAccounts,dc=csateng,dc=lab" -fn "Terrence" -ln "Chapman" -disabled no -display "Terrence Chapman" -desc "Radioactive Team Glacier Airset Caster" -office "DevLabs Radioactive Team Glacier" -title "Airset Caster" -company "DevLabs" -PWD "Badpass68831"
    DSADD user -upn Horace.Alvarado@csateng.lab "cn=Horace.Alvarado,ou=UserAccounts,dc=csateng,dc=lab" -fn "Horace" -ln "Alvarado" -disabled no -display "Horace Alvarado" -desc "Radioactive Team Glacier Counterintelligence/Human Intelligence, Senior Sergeant" -office "DevLabs Radioactive Team Glacier" -title "Counterintelligence/Human Intelligence, Senior Sergeant" -company "DevLabs" -PWD "Badpass13042"
    DSADD user -upn Jeannie.Jacobs@csateng.lab "cn=Jeannie.Jacobs,ou=UserAccounts,dc=csateng,dc=lab" -fn "Jeannie" -ln "Jacobs" -disabled no -display "Jeannie Jacobs" -desc "Radioactive Team Glacier Ship Purser" -office "DevLabs Radioactive Team Glacier" -title "Ship Purser" -company "DevLabs" -PWD "Badpass55527"
    DSADD user -upn Irvin.May@csateng.lab "cn=Irvin.May,ou=UserAccounts,dc=csateng,dc=lab" -fn "Irvin" -ln "May" -disabled no -display "Irvin May" -desc "Radioactive Team Glacier Poker Room Supervisor" -office "DevLabs Radioactive Team Glacier" -title "Poker Room Supervisor" -company "DevLabs" -PWD "Badpass60479"
    DSADD user -upn Rafael.Colon@csateng.lab "cn=Rafael.Colon,ou=UserAccounts,dc=csateng,dc=lab" -fn "Rafael" -ln "Colon" -disabled no -display "Rafael Colon" -desc "Radioactive Team Glacier Licensed Massage Therapist" -office "DevLabs Radioactive Team Glacier" -title "Licensed Massage Therapist" -company "DevLabs" -PWD "Badpass40962"
    DSADD user -upn Gertrude.Kim@csateng.lab "cn=Gertrude.Kim,ou=UserAccounts,dc=csateng,dc=lab" -fn "Gertrude" -ln "Kim" -disabled no -display "Gertrude Kim" -desc "Titanium Task Force Magnetic Fire Control Officer" -office "DevLabs Titanium Task Force Magnetic" -title "Fire Control Officer" -company "DevLabs" -PWD "Badpass87915"
    DSADD user -upn Angela.Knight@csateng.lab "cn=Angela.Knight,ou=UserAccounts,dc=csateng,dc=lab" -fn "Angela" -ln "Knight" -disabled no -display "Angela Knight" -desc "Titanium Task Force Magnetic Motor Rewinder" -office "DevLabs Titanium Task Force Magnetic" -title "Motor Rewinder" -company "DevLabs" -PWD "Badpass80578"
    DSADD user -upn Janie.Goodwin@csateng.lab "cn=Janie.Goodwin,ou=UserAccounts,dc=csateng,dc=lab" -fn "Janie" -ln "Goodwin" -disabled no -display "Janie Goodwin" -desc "Titanium Task Force Magnetic Airplane Refueler" -office "DevLabs Titanium Task Force Magnetic" -title "Airplane Refueler" -company "DevLabs" -PWD "Badpass83974"
    DSADD user -upn Stephen.Mckinney@csateng.lab "cn=Stephen.Mckinney,ou=UserAccounts,dc=csateng,dc=lab" -fn "Stephen" -ln "Mckinney" -disabled no -display "Stephen Mckinney" -desc "Titanium Task Force Magnetic Marine Architect" -office "DevLabs Titanium Task Force Magnetic" -title "Marine Architect" -company "DevLabs" -PWD "Badpass73138"
    DSADD user -upn Eleanor.Abbott@csateng.lab "cn=Eleanor.Abbott,ou=UserAccounts,dc=csateng,dc=lab" -fn "Eleanor" -ln "Abbott" -disabled no -display "Eleanor Abbott" -desc "Titanium Task Force Magnetic Harvest Crew Supervisor" -office "DevLabs Titanium Task Force Magnetic" -title "Harvest Crew Supervisor" -company "DevLabs" -PWD "Badpass68"
    DSADD user -upn Perry.Newman@csateng.lab "cn=Perry.Newman,ou=UserAccounts,dc=csateng,dc=lab" -fn "Perry" -ln "Newman" -disabled no -display "Perry Newman" -desc "Titanium Task Force Magnetic Compressor Station Operator" -office "DevLabs Titanium Task Force Magnetic" -title "Compressor Station Operator" -company "DevLabs" -PWD "Badpass2396"
    DSADD user -upn Dan.Richardson@csateng.lab "cn=Dan.Richardson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Dan" -ln "Richardson" -disabled no -display "Dan Richardson" -desc "Titanium Task Force Magnetic Street Sweeper Operator" -office "DevLabs Titanium Task Force Magnetic" -title "Street Sweeper Operator" -company "DevLabs" -PWD "Badpass6205"
    DSADD user -upn Kim.Dennis@csateng.lab "cn=Kim.Dennis,ou=UserAccounts,dc=csateng,dc=lab" -fn "Kim" -ln "Dennis" -disabled no -display "Kim Dennis" -desc "Titanium Task Force Magnetic Submarine Diver" -office "DevLabs Titanium Task Force Magnetic" -title "Submarine Diver" -company "DevLabs" -PWD "Badpass73923"
    DSADD user -upn Hattie.Henry@csateng.lab "cn=Hattie.Henry,ou=UserAccounts,dc=csateng,dc=lab" -fn "Hattie" -ln "Henry" -disabled no -display "Hattie Henry" -desc "Titanium Task Force Magnetic Paraeducator" -office "DevLabs Titanium Task Force Magnetic" -title "Paraeducator" -company "DevLabs" -PWD "Badpass49354"
    DSADD user -upn Katrina.Frazier@csateng.lab "cn=Katrina.Frazier,ou=UserAccounts,dc=csateng,dc=lab" -fn "Katrina" -ln "Frazier" -disabled no -display "Katrina Frazier" -desc "Titanium Task Force Magnetic Clinical Social Work Aide" -office "DevLabs Titanium Task Force Magnetic" -title "Clinical Social Work Aide" -company "DevLabs" -PWD "Badpass14909"
    DSADD user -upn Christie.Hubbard@csateng.lab "cn=Christie.Hubbard,ou=UserAccounts,dc=csateng,dc=lab" -fn "Christie" -ln "Hubbard" -disabled no -display "Christie Hubbard" -desc "Uranium Squadron Grocery Stocker" -office "DevLabs Uranium Squadron" -title "Grocery Stocker" -company "DevLabs" -PWD "Badpass91353"
    DSADD user -upn Johnnie.Doyle@csateng.lab "cn=Johnnie.Doyle,ou=UserAccounts,dc=csateng,dc=lab" -fn "Johnnie" -ln "Doyle" -disabled no -display "Johnnie Doyle" -desc "Uranium Squadron Laryngologist" -office "DevLabs Uranium Squadron" -title "Laryngologist" -company "DevLabs" -PWD "Badpass7531"
    DSADD user -upn Micheal.Mathis@csateng.lab "cn=Micheal.Mathis,ou=UserAccounts,dc=csateng,dc=lab" -fn "Micheal" -ln "Mathis" -disabled no -display "Micheal Mathis" -desc "Uranium Squadron Officer In Charge, Aviation Unit Or Detachment" -office "DevLabs Uranium Squadron" -title "Officer In Charge, Aviation Unit Or Detachment" -company "DevLabs" -PWD "Badpass97915"
    DSADD user -upn Maxine.James@csateng.lab "cn=Maxine.James,ou=UserAccounts,dc=csateng,dc=lab" -fn "Maxine" -ln "James" -disabled no -display "Maxine James" -desc "Uranium Squadron Chambermaid" -office "DevLabs Uranium Squadron" -title "Chambermaid" -company "DevLabs" -PWD "Badpass28066"
    DSADD user -upn Susie.Vargas@csateng.lab "cn=Susie.Vargas,ou=UserAccounts,dc=csateng,dc=lab" -fn "Susie" -ln "Vargas" -disabled no -display "Susie Vargas" -desc "Uranium Squadron Roof Truss Builder" -office "DevLabs Uranium Squadron" -title "Roof Truss Builder" -company "DevLabs" -PWD "Badpass63429"
    DSADD user -upn Gayle.Mullins@csateng.lab "cn=Gayle.Mullins,ou=UserAccounts,dc=csateng,dc=lab" -fn "Gayle" -ln "Mullins" -disabled no -display "Gayle Mullins" -desc "Uranium Squadron Refinery Process Engineer" -office "DevLabs Uranium Squadron" -title "Refinery Process Engineer" -company "DevLabs" -PWD "Badpass65072"
    DSADD user -upn Clayton.Vega@csateng.lab "cn=Clayton.Vega,ou=UserAccounts,dc=csateng,dc=lab" -fn "Clayton" -ln "Vega" -disabled no -display "Clayton Vega" -desc "Uranium Squadron Podiatric Aide" -office "DevLabs Uranium Squadron" -title "Podiatric Aide" -company "DevLabs" -PWD "Badpass89212"
    DSADD user -upn Lance.Reed@csateng.lab "cn=Lance.Reed,ou=UserAccounts,dc=csateng,dc=lab" -fn "Lance" -ln "Reed" -disabled no -display "Lance Reed" -desc "Uranium Squadron Certified Respiratory Therapy Technician" -office "DevLabs Uranium Squadron" -title "Certified Respiratory Therapy Technician" -company "DevLabs" -PWD "Badpass73785"
    DSADD user -upn Jon.Barrett@csateng.lab "cn=Jon.Barrett,ou=UserAccounts,dc=csateng,dc=lab" -fn "Jon" -ln "Barrett" -disabled no -display "Jon Barrett" -desc "Nano Spectral Sagittarius Ballerina" -office "DevLabs Nano Spectral Sagittarius" -title "Ballerina" -company "DevLabs" -PWD "Badpass82151"
    DSADD user -upn Leigh.Bell@csateng.lab "cn=Leigh.Bell,ou=UserAccounts,dc=csateng,dc=lab" -fn "Leigh" -ln "Bell" -disabled no -display "Leigh Bell" -desc "Nano Spectral Sagittarius Low Altitude Air Defense (Laad) Gunner" -office "DevLabs Nano Spectral Sagittarius" -title "Low Altitude Air Defense (Laad) Gunner" -company "DevLabs" -PWD "Badpass81599"
    DSADD user -upn Ernestine.Carson@csateng.lab "cn=Ernestine.Carson,ou=UserAccounts,dc=csateng,dc=lab" -fn "Ernestine" -ln "Carson" -disabled no -display "Ernestine Carson" -desc "Nano Spectral Sagittarius Offset Lithographic Press Setter and Set-Up Operator" -office "DevLabs Nano Spectral Sagittarius" -title "Offset Lithographic Press Setter and Set-Up Operator" -company "DevLabs" -PWD "Badpass23341"
    DSADD user -upn Martha.Maldonado@csateng.lab "cn=Martha.Maldonado,ou=UserAccounts,dc=csateng,dc=lab" -fn "Martha" -ln "Maldonado" -disabled no -display "Martha Maldonado" -desc "Nano Spectral Sagittarius Financial Director" -office "DevLabs Nano Spectral Sagittarius" -title "Financial Director" -company "DevLabs" -PWD "Badpass14969"
    DSADD user -upn Calvin.Powell@csateng.lab "cn=Calvin.Powell,ou=UserAccounts,dc=csateng,dc=lab" -fn "Calvin" -ln "Powell" -disabled no -display "Calvin Powell" -desc "Nano Spectral Sagittarius Milking Machine Mechanic" -office "DevLabs Nano Spectral Sagittarius" -title "Milking Machine Mechanic" -company "DevLabs" -PWD "Badpass34364"
    DSADD user -upn Cathy.Schultz@csateng.lab "cn=Cathy.Schultz,ou=UserAccounts,dc=csateng,dc=lab" -fn "Cathy" -ln "Schultz" -disabled no -display "Cathy Schultz" -desc "Nano Spectral Sagittarius County Surveyor" -office "DevLabs Nano Spectral Sagittarius" -title "County Surveyor" -company "DevLabs" -PWD "Badpass53098"
    DSADD user -upn Phyllis.Washington@csateng.lab "cn=Phyllis.Washington,ou=UserAccounts,dc=csateng,dc=lab" -fn "Phyllis" -ln "Washington" -disabled no -display "Phyllis Washington" -desc "Nano Spectral Sagittarius Oil Pipeline Dispatcher" -office "DevLabs Nano Spectral Sagittarius" -title "Oil Pipeline Dispatcher" -company "DevLabs" -PWD "Badpass75024"
    DSADD user -upn Homer.Simmons@csateng.lab "cn=Homer.Simmons,ou=UserAccounts,dc=csateng,dc=lab" -fn "Homer" -ln "Simmons" -disabled no -display "Homer Simmons" -desc "Nano Spectral Sagittarius Service Order Clerk" -office "DevLabs Nano Spectral Sagittarius" -title "Service Order Clerk" -company "DevLabs" -PWD "Badpass92861"
    DSADD user -upn Delores.Wright@csateng.lab "cn=Delores.Wright,ou=UserAccounts,dc=csateng,dc=lab" -fn "Delores" -ln "Wright" -disabled no -display "Delores Wright" -desc "Nano Spectral Sagittarius City Alderman" -office "DevLabs Nano Spectral Sagittarius" -title "City Alderman" -company "DevLabs" -PWD "Badpass68246"
    DSADD user -upn Amos.Edwards@csateng.lab "cn=Amos.Edwards,ou=UserAccounts,dc=csateng,dc=lab" -fn "Amos" -ln "Edwards" -disabled no -display "Amos Edwards" -desc "Nano Spectral Sagittarius CEO" -office "DevLabs Nano Spectral Sagittarius" -title "CEO" -company "DevLabs" -PWD "Badpass4921"
    DSADD user -upn Roy.Cross@csateng.lab "cn=Roy.Cross,ou=UserAccounts,dc=csateng,dc=lab" -fn "Roy" -ln "Cross" -disabled no -display "Roy Cross" -desc "Nano Spectral Sagittarius Chief Executive Officer" -office "DevLabs Nano Spectral Sagittarius" -title "Chief Executive Officer" -company "DevLabs" -PWD "Badpass13822"
    DSADD user -upn Alberta.Armstrong@csateng.lab "cn=Alberta.Armstrong,ou=UserAccounts,dc=csateng,dc=lab" -fn "Alberta" -ln "Armstrong" -disabled no -display "Alberta Armstrong" -desc "Nano Spectral Sagittarius Chief Operating Officer" -office "DevLabs Nano Spectral Sagittarius" -title "Chief Operating Officer" -company "DevLabs" -PWD "Badpass78144"
    DSADD user -upn Rochelle.Hughes@csateng.lab "cn=Rochelle.Hughes,ou=UserAccounts,dc=csateng,dc=lab" -fn "Rochelle" -ln "Hughes" -disabled no -display "Rochelle Hughes" -desc "Nano Spectral Sagittarius Commissioner of Internal Revenue" -office "DevLabs Nano Spectral Sagittarius" -title "Commissioner of Internal Revenue" -company "DevLabs" -PWD "Badpass16043"
    DSADD user -upn Irene.Houston@csateng.lab "cn=Irene.Houston,ou=UserAccounts,dc=csateng,dc=lab" -fn "Irene" -ln "Houston" -disabled no -display "Irene Houston" -desc "Nano Spectral Sagittarius COO" -office "DevLabs Nano Spectral Sagittarius" -title "COO" -company "DevLabs" -PWD "Badpass51156"
    DSADD user -upn Byron.Lawrence@csateng.lab "cn=Byron.Lawrence,ou=UserAccounts,dc=csateng,dc=lab" -fn "Byron" -ln "Lawrence" -disabled no -display "Byron Lawrence" -desc "Nano Spectral Sagittarius County Commissioner" -office "DevLabs Nano Spectral Sagittarius" -title "County Commissioner" -company "DevLabs" -PWD "Badpass74862"
    DSADD user -upn Marion.Gonzalez@csateng.lab "cn=Marion.Gonzalez,ou=UserAccounts,dc=csateng,dc=lab" -fn "Marion" -ln "Gonzalez" -disabled no -display "Marion Gonzalez" -desc "Nano Spectral Sagittarius Government Service Executive" -office "DevLabs Nano Spectral Sagittarius" -title "Government Service Executive" -company "DevLabs" -PWD "Badpass62004"
    DSADD user -upn Gerald.Wade@csateng.lab "cn=Gerald.Wade,ou=UserAccounts,dc=csateng,dc=lab" -fn "Gerald" -ln "Wade" -disabled no -display "Gerald Wade" -desc "Nano Spectral Sagittarius City Alderman" -office "DevLabs Nano Spectral Sagittarius" -title "City Alderman" -company "DevLabs" -PWD "Badpass35101"
    DSADD user -upn Donna.Garner@csateng.lab "cn=Donna.Garner,ou=UserAccounts,dc=csateng,dc=lab" -fn "Donna" -ln "Garner" -disabled no -display "Donna Garner" -desc "Compu Matrix M City Council Member" -office "DevLabs Compu Matrix M" -title "City Council Member" -company "DevLabs" -PWD "Badpass63050"

    Remove-Item "c:\stage1complete.txt"
    Remove-Item "c:\stage2complete.txt"

}